### ISSUE TITLE
Debug data takes up too much resource

### ISSUE THREAD

**Issue by Fungus-00** [sakura-ryoko/servux#16]
Server version: 1.21.3
Fabric Loader: 0.16.9
Fabric API: 0.108.0
Servux version: 0.4.0-sakura.5

1. As an operator, when I enter the server, my network broadband is full (10MB/s+) and I can not load chunk as normal, while non-op doesn't has such problem. It is due to a mass of debug data sent by servux, though I'm not sure what exactly servux is sending.
2. If there are hundreds or even thounds of living entities with brian stuck in a narrow space (with climbable blocks they don't suffocate), even if other vast redundant calculations are optimized by certain mods, servux takes up the rest of resources.
![Calculation of Piglin, by Spark, in Yarn mapping](https://github.com/user-attachments/assets/e6f7687c-cd5b-4d6e-b2eb-b95fe536108b)
3. It seems that `config/servux.json` in server cannot be modified validly, as it comes back to the origin after the server restart, at least for the value of `DataProviderToggles`. So that `debug_data` config might not able to be disabled.

I have no idea of what debug data, which merged from a DEV branch of servux, exactly does, but I think most people don't really need this and yet it brings troubles. So please make it disabled as default.

**Comment by sakura-ryoko** [comment]
changed the default and made the config loading / changes for setting the data providers on and off to be more bearable.

Also, the `debug_data` service is another MiniHUD based protocol for sending the Vanilla Debug Renderer data.  I knew that it generates a lot of excess traffic, so that's why I put it being OP level by default; and the users need to manually "register" their clients with Servux for it to even start sending them data using MiniHUD's `debugDataMainToggle` config.

MiniHUD also has the same `DebugDataManager` for when you are playing in Single Player.  This makes it so that the various Vanilla debug Renderer's work.

These packets are sent ***every single game tick*** in the Server thread for ***every single nearby entity***

But without this option, at least in Single Player (or using Servux's `debug_data`); your Path finding and other Debug Renderers will not function.  I tried to make these descriptions rather obvious in the config comments for each of the debug renderer options, as to which ones requires Server data.

**Comment by sakura-ryoko** [comment]
Should be in the next update

**Comment by sakura-ryoko** [comment]
If you need faster relief, download the build artifact -->
https://github.com/sakura-ryoko/servux/actions/runs/11883319135

**Comment by sakura-ryoko** [comment]
See --> https://github.com/sakura-ryoko/servux/releases/tag/1.21.3-0.4.0-sakura.6
